import { Platform, StatusBar, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    justifyContent: "flex-start",
    width: "100%",
    height: "100%",
    marginTop: (Platform.OS === 'ios') ? 80 : (StatusBar.currentHeight ? (StatusBar.currentHeight + 80) : 80),
  },

  infoTextContainer: {
    width: "95%",
    paddingTop: "5%",
    paddingBottom: "12%",
    paddingHorizontal: "8%",
    alignSelf: "center",
    alignItems: "flex-start",
    justifyContent: "space-around",
  },
  infoText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "300",
    marginTop: 3,
    letterSpacing: 1,
  },
  addSpotButton: {
    width: "100%",
    height: "100%",
    backgroundColor: "#fff",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 25,
  },
  addSpotButtonText: {
    color: "#000",
    fontSize: 15,
    fontWeight: "400",
  },

  credentialParentContainer: {
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    height: "65%",
    width: "95%",
    alignItems: "center",
    paddingVertical: "5%",
    alignSelf: "center",
    justifyContent: "space-around",
    marginTop: "3%",
    borderColor: "#555",
    borderWidth: 3,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 0,
  },
  credentialParentContainerLg: {
    height: "70%",
  },
  headerText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "300",
    letterSpacing: 1,
    marginHorizontal: 25,
  },
  credentialContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderBottomWidth: 1,
    borderBottomColor: "#fff",
    height: "15%",
    width: "85%",
    paddingBottom: 5,
  },
  credential: {
    color: "#fff",
    fontSize: 16,
    paddingLeft: 5,
    width: "85%"
  },
  buttonContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginRight: 5,
  },
  buttons: {
    flex: 0.4,
    aspectRatio: 1,
  },
  buttonForAddress: {
    flex: 0.5,
    paddingBottom: 3,
  },
  checkBoxContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: "10%",
    width: "85%",
    marginTop: 25,
    paddingHorizontal: 25,
    backgroundColor: "#fff",
    borderRadius: 25,
  },
  checkBox: {
    height: "100%",
    justifyContent: "center",
  },
  checkBoxText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "300",
  },

  termsAndConditionsHeader: {
    color: "#fff",
    fontSize: 20,
    letterSpacing: 2,
    fontWeight: "300",
    marginRight: 20,
    alignSelf: "flex-start",
    marginLeft: 22,
    marginBottom: 15,
  },
  termsAndConditionsContainer: {
    height: "75%",
    margin: 20,
    marginBottom: 0,
    padding: 25,
    paddingTop: 20,
    paddingRight: 15,
    borderColor: "#fff",
    borderWidth: 1,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 0,
  },
  termsAndConditions: {
    color: "#fff",
    fontSize: 15,
    letterSpacing: 2,
    fontWeight: "300",
    marginRight: 20,
    alignSelf: "center",
    textAlign: "center",
  },
  scrollBarContainer: {
    position: "absolute",
    right: 2,
    backgroundColor: "#ccc",
    width: 10,
    height: "102%",
    paddingTop: 10,
    marginTop: 18,
    marginRight: 10,
    borderTopRightRadius: 50,
    borderBottomRightRadius: 0,
  },

  addCostPlanButtonConatiner: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    justifyContent: "space-evenly",
    backgroundColor: "#fff",
    borderRadius: 150,
    width: "50%",
    height: 40,
    margin: 20,
    marginTop: 5,
  },
  addCostPlanButton: {
    flex: 0.3,
    aspectRatio: 1,
  },
  addCostPlanButtonText: {
    color: "#000",
    fontSize: 15,
    fontWeight: "400",
  },
  costContainer: {
    flexDirection: "row",
    width: "95%",
    justifyContent: "space-around",
    alignItems: "center",
    paddingHorizontal: 5,
    marginVertical: 15,
  },
  costInput: {
    color: "#fff",
    fontSize: 16,
    borderColor: "#fff",
    borderBottomWidth: 1,
    height: 40,
    width: "35%",
  },
  perText: {
    width: "10%",
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
  },
  dropdown: {
    height: 45,
    width: "40%",
    borderColor: '#fff',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 5,
  },
  placeholderStyle: {
    color: "#fff",
    fontSize: 15,
  },
  selectedTextStyle: {
    fontSize: 15,
  },
  iconStyle: {
    width: 25,
    height: 25,
  },
  removeCostPlanButtonContainer: {
    width: "1%",
    height: 45,
    justifyContent: "center",
    paddingLeft: 5,
    alignSelf: "flex-start",
  },
  removeCostPlanButton: {
    flex: 0.5,
    aspectRatio: 1,
  },

  detailsContainer: {
    alignItems: "flex-start",
    paddingHorizontal: 25,
    paddingBottom: 0,
    marginRight: 12,
    paddingRight: 12,
  },

  warningText: {
    color: "orange",
    fontSize: 13,
    marginTop: 25,
    alignSelf: "flex-start",
    marginLeft: 25,
  },

  nextBackButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    width: "100%",
    height: "15%",
    paddingHorizontal: "5%",
    marginTop: 30,
  },
  backButton: {
    width: "45%",
    height: "85%",
    borderColor: "#fff",
    borderWidth: 2,
    borderRadius: 25,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  backAndNextButtonIcon: {
    flex: 0.25,
    aspectRatio: 1,
  },
  backButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "300",
    marginRight: 25,
  },
  nextButton: {
    width: "45%",
    height: "85%",
    backgroundColor: "#fff",
    borderRadius: 25,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  nextButtonText: {
    color: "#000",
    fontSize: 15,
    fontWeight: "300",
    marginLeft: 25,
  },
})

export default styles;