import { Platform, StatusBar, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    justifyContent: "flex-start",
    width: "100%",
    height: "100%",
    marginTop: (Platform.OS === 'ios') ? 80 : (StatusBar.currentHeight ? (StatusBar.currentHeight + 80) : 80),
  },

  infoTextContainer: {
    paddingTop: 15,
    paddingBottom: 25,
    paddingHorizontal: 25,
    alignSelf: "center",
    alignItems: "flex-start",
    justifyContent: "space-around",
  },
  infoText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "300",
    marginTop: 3,
    letterSpacing: 1,
  },
  addSpotButton: {
    width: "100%",
    height: "100%",
    backgroundColor: "#fff",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  addSpotButtonText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "400",
  },

  credentialParentContainer: {
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    height: "70%",
    width: "95%",
    alignItems: "center",
    paddingVertical: 30,
    alignSelf: "center",
    justifyContent: "space-evenly",
    marginTop: 10,
    borderColor: "#555",
    borderWidth: 3,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 0,
  },

  headerText: {
    textAlign: "left",
    alignSelf: "flex-start",
    color: "#fff",
    fontSize: 18,
    fontWeight: "300",
    letterSpacing: 1,
    marginHorizontal: 25,
    marginBottom: 25,
  },
  credentialContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#888",
    height: 42,
    margin: 10,
    width: "85%",
  },
  credential: {
    color: "#fff",
    fontSize: 16,
    paddingLeft: 5,
    fontWeight: "300",
    letterSpacing: 1,
    width: "85%"
  },
  buttonContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginRight: 5,
  },
  buttons: {
    flex: 0.4,
    aspectRatio: 1,
  },
  buttonForAddress: {
    flex: 0.5,
    paddingBottom: 3,
  },
  checkBoxContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: 40,
    width: "85%",
    paddingHorizontal: 25,
    backgroundColor: "#fff",
    borderRadius: 25,
    marginBottom: 25,
  },
  checkBox: {
    height: "100%",
    justifyContent: "center",
  },
  checkBoxText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "300",
  },

  addCostPlanButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    justifyContent: "space-evenly",
    backgroundColor: "#fff",
    borderRadius: 150,
    width: "50%",
    height: 40,
    margin: 20,
    marginTop: 3,
  },
  addCostPlanButton: {
    flex: 0.3,
    aspectRatio: 1,
  },
  addCostPlanButtonText: {
    color: "#000",
    fontSize: 15,
    fontWeight: "400",
  },
  costContainer: {
    flexDirection: "row",
    width: "98%",
    justifyContent: "space-around",
    alignItems: "center",
    paddingHorizontal: 5,
    marginVertical: 15,
  },
  costInput: {
    color: "#fff",
    textAlign: "center",
    fontSize: 16,
    borderColor: "#888",
    borderWidth: 1,
    borderRadius: 5,
    height: 48,
    width: "30%",
  },
  perText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
  },
  dropdown: {
    height: 48,
    width: "45%",
    borderColor: '#888',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 3,
  },
  placeholderStyle: {
    color: "#fff",
    fontSize: 15,
  },
  selectedTextStyle: {
    fontSize: 15,
  },
  iconStyle: {
    width: 25,
    height: 25,
  },
  removeCostPlanButtonContainer: {
    width: "1%",
    height: 45,
    justifyContent: "center",
    marginRight: 2,
    alignSelf: "flex-start",
  },
  removeCostPlanButton: {
    flex: 0.4,
    aspectRatio: 1,
  },

  termsAndConditionsContainer: {
    height: "70%",
    marginHorizontal: 15,
    marginBottom: 25,
    padding: 25,
    paddingTop: 20,
    paddingRight: 15,
    borderColor: "#888",
    borderWidth: 1,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 0,
  },
  termsAndConditions: {
    color: "#fff",
    fontSize: 15,
    letterSpacing: 2.5,
    fontWeight: "300",
    fontStyle: "italic",
    marginRight: 20,
  },
  scrollBarContainer: {
    position: "absolute",
    right: 2,
    backgroundColor: "#ccc",
    width: 10,
    height: "102%",
    paddingTop: 10,
    marginTop: 18,
    marginRight: 10,
    borderTopRightRadius: 50,
    borderBottomRightRadius: 0,
  },

  confirmationContainer: {
    width: "90%",
    height: "75%",
    alignSelf: "center",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderColor: "#555",
    borderWidth: 1,
    borderRadius: 15,
    marginBottom: 25,
  },
  confirmationItem: {
    marginVertical: 5,
  },
  confirmationHead: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "200",
    letterSpacing: 0.5,
    fontStyle: "italic",
    marginBottom: 1.5,
  },
  confirmationData: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "400",
  },

  warningText: {
    color: "orange",
    fontSize: 13,
    marginTop: 25,
    alignSelf: "flex-start",
    marginLeft: 25,
  },

  seperator: {
    borderColor: "#fff",
    borderWidth: 0.5,
    width: "95%",
    marginVertical: 10,
  },

  nextBackButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    width: "100%",
    height: "15%",
    paddingHorizontal: "5%",
    marginBottom: 25,
  },
  backButton: {
    width: "45%",
    height: "85%",
    borderColor: "#fff",
    borderWidth: 2,
    borderRadius: 25,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  backAndNextButtonIcon: {
    flex: 0.25,
    aspectRatio: 1,
  },
  backButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "300",
    marginRight: 25,
  },
  nextButton: {
    width: "45%",
    height: "85%",
    backgroundColor: "#fff",
    borderRadius: 25,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  nextButtonText: {
    color: "#000",
    fontSize: 15,
    fontWeight: "300",
    marginLeft: 25,
  },
})

export default styles;